"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Normative records schema - adapted from https://raw.githubusercontent.com/opengeospatial/ogcapi-records/master/core/openapi/schemas/recordGeoJSON.yaml'
type: object
allOf:
  - $ref: bblocks://ogc.geo.features.feature
required:
  - id
  - type
  - geometry
  - properties
  - links
properties:
  id:
    type: string
    description:
      A unique identifier of the catalog record.
    format: uri
  conformsTo:
    type: array
    items:
      type: string
  type:
    type: string
    enum:
      - Feature
  time:
    oneOf:
      - enum:
        - null
      - $ref: 'bblocks://ogc.api.records.v1.schemas.time'
  geometry:
    oneOf:
      - enum:
        - null
      - $ref: 'https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/geometryGeoJSON.yaml'
  properties:
    type: object
    required:
      - type
      - title
    properties:
      created:
        type: string
        description:
          Date of creation of this record.
        format: date-time
      updated:
        type: string
        description:
          The most recent date on which the record was changed.
        format: date-time
      type:
        type: string
        description:
          The nature or genre of the resource. The value
          should be a code, convenient for filtering
          records. Where available, a link to the canonical
          URI of the record type resource will be added to
          the 'links' property.
        maxLength: 64
      title:
        type: string
        description:
          A human-readable name given to the resource.
      description:
        type: string
        description:
          A free-text account of the resource.
      keywords:
        type: array
        description:
          The topic or topics of the resource. Typically
          represented using free-form keywords, tags, key
          phrases, or classification codes.
        items:
          type: string
      language:
        description:
          The language used for textual values in this
          record representation.
        $ref: 'bblocks://ogc.api.records.v1.schemas.language'
      languages:
        type: array
        description:
          This list of languages in which this record is
          available.
        items:
          $ref: 'bblocks://ogc.api.records.v1.schemas.language'
      resourceLanguages:
        type: array
        description:
          The list of languages in which the resource
          described by this record is available.
        items:
          $ref: 'bblocks://ogc.api.records.v1.schemas.language'
      externalIds:
        type: array
        description:
          An identifier for the resource assigned by an
          external (to the catalog) entity.
        items:
          type: object
          properties:
            scheme:
              type: string
              description:
                A reference to an authority or identifier
                for a knowledge organization system from
                which the external identifier was obtained.
                It is recommended that the identifier be a
                resolvable URI.
            value:
              type: string
              description: The value of the identifier.
          required:
            - value
      themes:
        type: array
        description:
          A knowledge organization system used to classify
          the resource.
        minItems: 1
        items:
          $ref: 'bblocks://ogc.api.records.v1.schemas.theme'
      formats:
        type: array
        description:
          A list of available distributions of the resource.
        items:
          type: string
      contacts:
        type: array
        description:
          A list of contacts qualified by their role(s) in
          association to the record or the resource described
          by the record.
        items:
          $ref: 'bblocks://ogc.api.records.v1.schemas.contact'
      license:
        $ref: 'bblocks://ogc.api.records.v1.schemas.license'
      rights:
        type: string
        description:
          A statement that concerns all rights not addressed
          by the license such as a copyright statement.
  links:
    type: array
    items:
      $ref: 'bblocks://ogc.ogc-utils.json-link'
  linkTemplates:
    type: array
    items:
      $ref: 'bblocks://ogc.api.records.v1.schemas.linkTemplate'


