"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Normative records schema'
allOf:
  - $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-records/master/core/openapi/schemas/recordGeoJSON.yaml

