$comment: Adapted from https://github.com/opengeospatial/ogcapi-records/raw/master/core/openapi/schemas/link.yaml
type: object
allOf:
  - $ref: bblocks://ogc.api.records.v1.schemas.linkBase
  - type: object
    required:
      - href
    properties:
      href:
        allOf:
          - type: string
            format: uri
          # TODO: Re-enable requirement, but also support relative paths (`./collection.yaml`)
          # - $ref: bblocks://ogc.ogc-utils.iri-or-curie#/$defs/IRI
