name: Validate and process Building Blocks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 */3 * *"
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-process:
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
    # with:
    #   sparql_username: sparql
    #   sparql_password: Secr3T
